#Build commands for assembling main application code using Codebuild managed Linux container..
version: 0.2
phases:
  pre_build:
    commands:
      - echo logging in to Amazon ECR for new $Branch image upload...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $Ecr
      - export uniquetag=$(date +%Y%m%d%H%M%S)
  build:
    commands:
      - service docker start
      - echo Building the Docker image on for $Branch...
      - docker build -t $Branch .
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag $Branch:latest $Ecr/nfts:$Branch$uniquetag
      - docker push $Ecr/nfts:$Branch$uniquetag
        
  post_build:
    commands:
      - echo Updating the Lambda function code to use the new $Branch Docker image...
      - aws lambda update-function-code --function-name MainLambdaMS$projectid --image-uri $Ecr/nfts:$Branch$uniquetag