#Build commands for building docker image from source repo Dockerfile..
version: 0.2
phases:
  pre_build:
    commands:
      - echo logging in to Amazon ECR for new $Branch image upload...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $Ecr
      - export uniquetag=$(date +%Y%m%d%H%M%S)
  build:
    commands:
      - echo Building the Docker image for image repo nft$Branch...
      - docker build -t nft$Branch:$uniquetag .
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag nft$Branch:$uniquetag $Ecr/nft$Branch:$uniquetag
      - docker push $Ecr/nft$Branch:$uniquetag
        
  post_build:
    commands:
      - echo Updating the Lambda function code to use the new $Branch Docker image...
      - aws lambda update-function-code --function-name MainLambdaMS$projectid --image-uri $Ecr/nft$Branch:$uniquetag