#Build commands for building docker image from source repo Dockerfile....
#TODO figure out if the correct image is being sources to the respective lambda alias version
version: 0.2
phases:
  pre_build:
    #phase for logging into docker through aws using repo uri. and creating image id
    commands:
      - echo logging in to Amazon ECR for new $Branch image upload...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $Ecr
      - export uniquetag=$(date +%Y%m%d%H%M%S)
  build:
    #phase for building and pushing image to ECR
    commands:
      - echo Building the Docker image for image repo $EcrRepoName...
      - docker build -t $EcrRepoName:$uniquetag .
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag $EcrRepoName:$uniquetag $Ecr/$EcrRepoName:$uniquetag
      - docker push $Ecr/$EcrRepoName:$uniquetag
        
  post_build:
    #update lambda microservice 
    commands:
      - echo Updating the Lambda function code to use the new $Branch Docker image...
      - aws lambda update-function-code --function-name MainLambdaMS$Branch$projectid --image-uri $Ecr/$EcrRepoName:$uniquetag --publish