AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    accesscreds:
        Type: String


Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            InstanceType: t2.micro
            IamInstanceProfile: !Ref Developmentenvprofile
            ImageId: ami-0aa7d40eeae50c9a9
            KeyName: !Ref accesscreds
            SecurityGroups:
                - !Ref EC2InstanceSecurityGroup
            UserData: 
                Fn::Base64: |
                    #!/bin/bash
                    sudo yum install -y python3-pip
                    pip3 install boto3
            BlockDeviceMappings:
                -   DeviceName: "/dev/xvda"
                    Ebs:
                        VolumeSize: 8
                        VolumeType: gp2
    EC2InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow SSH access
            SecurityGroupIngress:
                -   IpProtocol: tcp
                    FromPort: 22
                    ToPort: 22
                    CidrIp: 0.0.0.0/0
    Developmentenvprofile:        
        Type: AWS::IAM::InstanceProfile
        Properties: 
            InstanceProfileName: 'Devenvprofile'
            Path: '/'
            Roles: 
                - !Ref Environmentrole
    Environmentrole:
        Type: AWS::IAM::Role
        Properties:    
            RoleName: 'DevEnvRole'
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   Effect: Allow
                        Principal:
                            Service: 
                                - 'ec2.amazonaws.com'
                        Action: 
                            - 'sts:AssumeRole'
            Policies:
                -   PolicyName: root                    
                    PolicyDocument:
                        Version: "2012-10-17"
                        Statement: 
                            -   Effect: Allow
                                Action: '*'
                                Resource: '*'